# Generated by Django 4.0.2 on 2022-02-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0002_fad'),
    ]

    operations = [
        migrations.AddField(
            model_name='fad',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fad',
            name='image_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fad',
            name='name',
            field=models.CharField(default='no name', max_length=100),
        ),
    ]
