# Generated by Django 4.0.2 on 2022-02-02 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='no name')),
                ('image_url', models.TextField(default='no image URL')),
                ('description', models.TextField(default='no description')),
                ('decade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decades', to='nostaldja.decade')),
            ],
        ),
    ]
