# Generated by Django 4.0.2 on 2022-02-01 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0001_initial'),
    ]

    operations = [
    ]
