# Generated by Django 4.0.2 on 2022-02-03 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0002_auto_20220203_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fads',
            name='decade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fad', to='tunr.decades'),
        ),
    ]
